# 1️⃣ Build
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# 2️⃣ Nginx ile serve
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# React router için
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
